blank_issues_enabled: false
contact_links:
  - name: Support/Questions
    url: https://discordapp.com/users/701726630233767996/
    about: For Questions and Support message me on discord (link above)
