name: Mod suggestion
description: Suggest an mod for this modpack
labels: mod
body:
- type: checkboxes
  attributes:
    label: Have you checked there is already an existing issue for this
    description: Before you request it, have you searched [here](https://github.com/Madis0/fabulously-optimized/issues) if it has already been requested by someone
    options:
    - label: I have searched for existing issues and found nothing.
      required: true
- type: input
  attributes:
    label: Mod name
  validations:
    required: true

- type: input
  attributes:
    label: Link to the mod
  validations:
    required: true

- type: textarea
  attributes:
    label: What does it do
    description: What does the mod do.
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it be in the Faster than light
    description: How can everyone profit from the mod while keeping the experience "vanilla-ish"?
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it not be in the modpack
    description: Don't forget to include any disadvantages of the mod.
    placeholder: |
      Examples: Still in alpha, ...
  validations:
      required: true

- type: dropdown
  attributes:
    label: Categories
    description: Select all that match the mod.
    multiple: true
    options:
      - Performance improvements
      - Graphics improvements
      - New feature
      - Works like Optifine/Forge/etc
      - Fixes a bug
      - Replaces an already existing mod
  validations:
    required: true

- type: textarea
  attributes:
    label: Other details
    description: Anything else you want to say to convince me?
  validations:
    required: false
